site_name: Getting a LUSEC Destop project
nav:
    - Home: index.md
    #- Svenska: index-sv.md
    
theme: readthedocs

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
#  - pymdownx.details
#  - pymdownx.superfences